### ISSUE TITLE
sizeof readings are strange

### ISSUE THREAD

**Issue by potswa** [jamboree/CxxFunctionBenchmark#18]
Since merging #17 and fixing the build, README.md says that cxx_function and Boost went from 32 bytes (4 pointers) to 40 bytes. I can't reproduce this. I wonder what is special about @jamboree's build environment?

This is sort-of a bug in the benchmark (Boost really should have ABI stability), but also I'm curious whether this unknown factor is one I can detect and tolerate.

**Comment by jamboree** [comment]
Did you compare the result with earlier commit? Note that previous result is provided by @user706 run on 64-bit/g++6.3.0/Debian, while the new result is with my 64-bit/Visual Studio 15.8.9, and the Boost version may also differ.

You can reproduce the `boost::function` size online with MSVC [here](https://godbolt.org/z/zivFIQ).

**Comment by potswa** [comment]
Thanks! It's just the MSVC ABI.
