### ISSUE TITLE
Allocator support

### ISSUE THREAD

**Issue by FrankHB** [jamboree/CxxFunctionBenchmark#22]
Please add tests for allocators when supported, at least with the default allocators.

Moreover, `polymorphic_allocator` with pool resources can be used when available. See also [here](https://github.com/FrankHB/YSLib/blob/master/YBase/include/ystdex/memory_resource.h) for a C++11-ready implementation.

**Comment by jamboree** [comment]
This is probably out of the scope of this benchmark, which mainly focuses on invoke time. And, AFAICT, allocator support for `std::function` is removed in C++17, so I don't think it's worth the effort.

**Comment by FrankHB** [comment]
Well, it's fair to focus on invocation time; however, this policy is neither implied by the project name, nor interpreted in documents. OTOH, some related benchmarks (like [this](https://github.com/NoAvailableAlias/signal-slot-benchmarks/tree/master/#performance)) do including measurement on construction performance.

One more point to clarify: allocator support [is removed](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0302r1.html) by requisition from [some vendors](https://github.com/aws/aws-sdk-cpp/issues/652) due to premature designs (which is defective and never implemented portably in reality). That does not mean allocator interface is not needed. New proposed ones (e.g. [[1]](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0043r0.pdf)[[2]](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4758.html#func.wrap.func)) may still support the feature. It is propably worth reconsidering in future.

**Comment by jamboree** [comment]
>this policy is neither implied by the project name, nor interpreted in documents

OK. I edited the project description to clarify that.
